#!/usr/bin/env python3
"""Module D — publication-grade report generator.

Renders a 6-section scientific report (Title, Summary, Introduction, Methods,
Results, Interpretations) to HTML (Jinja2) and DOCX (python-docx). It is a pure
RENDERER: it emits only the real content passed to it (produced by the platform's
verified analyses). It never invents scientific prose or numbers; a missing
section is rendered as "— (not provided)".

Reads JSON on stdin, prints JSON {status, html, docxBase64}. Honest 'unavailable'
if the rendering libraries are missing.

Payload: { "title": str, "summary": str, "introduction": str, "methods": str,
           "results": str, "interpretations": str,
           "tables": [{"title","columns","rows"}], "formats": ["html","docx"] }
"""
import base64
import io
import json
import sys

PALETTE = {"bg": "#FFFFFF", "primary": "#0A192F", "accent": "#00B4D8", "neutral": "#F8F9FA"}
SECTIONS = [("summary", "Summary"), ("introduction", "Introduction"),
            ("methods", "Methods"), ("results", "Results"),
            ("interpretations", "Interpretations")]

HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title>{{ title }}</title>
<style>
  :root { --bg:{{ p.bg }}; --primary:{{ p.primary }}; --accent:{{ p.accent }}; --neutral:{{ p.neutral }}; }
  body { background:var(--bg); color:var(--primary); font-family:'Inter',system-ui,sans-serif; max-width:860px; margin:2rem auto; padding:0 1.25rem; line-height:1.6; }
  h1 { color:var(--primary); border-bottom:3px solid var(--accent); padding-bottom:.4rem; }
  h2 { color:var(--primary); margin-top:2rem; border-left:4px solid var(--accent); padding-left:.6rem; }
  .meta { color:#5b6b82; font-size:.85rem; }
  table { border-collapse:collapse; width:100%; margin:1rem 0; font-size:.9rem; }
  th { background:var(--primary); color:#fff; text-align:left; padding:.5rem .6rem; }
  td { border-bottom:1px solid #e3e8ef; padding:.45rem .6rem; }
  tr:nth-child(even) td { background:var(--neutral); }
  code, .mono { font-family:'Fira Code','JetBrains Mono',monospace; }
  .muted { color:#8a97a8; font-style:italic; }
</style></head>
<body>
  <h1>{{ title }}</h1>
  <p class="meta">Generated by the Advanced Bioinformatics Platform (SynOmics) · {{ generated }}</p>
  {% for key, label in sections %}
  <h2>{{ label }}</h2>
  {% if content.get(key) %}<div>{{ content[key] }}</div>{% else %}<div class="muted">— (not provided)</div>{% endif %}
  {% endfor %}
  {% if tables %}
  <h2>Tables</h2>
  {% for t in tables %}
    <h3>{{ t.get('title','Table') }}</h3>
    <table><thead><tr>{% for c in t.get('columns',[]) %}<th>{{ c }}</th>{% endfor %}</tr></thead>
    <tbody>{% for row in t.get('rows',[]) %}<tr>{% for cell in row %}<td class="mono">{{ cell }}</td>{% endfor %}</tr>{% endfor %}</tbody></table>
  {% endfor %}
  {% endif %}
</body></html>"""


def _fail(msg, status="unavailable"):
    print(json.dumps({"status": status, "error": msg}))
    sys.exit(0)


def main():
    try:
        raw = sys.stdin.read()
        payload = json.loads(raw) if raw.strip() else {}
    except Exception as e:
        _fail(f"Invalid JSON payload: {e}", status="error")

    title = payload.get("title")
    if not title:
        _fail("A report `title` is required.", status="error")
    formats = payload.get("formats") or ["html", "docx"]
    import datetime
    generated = datetime.datetime.now(datetime.timezone.utc).isoformat()
    content = {k: payload.get(k) for k, _ in SECTIONS}
    tables = payload.get("tables") or []

    out = {"status": "success", "title": title, "sections": [k for k, _ in SECTIONS]}

    if "html" in formats:
        try:
            from jinja2 import Template
        except Exception as e:
            _fail(f"HTML report requires jinja2: {e}")
        out["html"] = Template(HTML_TEMPLATE).render(
            title=title, p=PALETTE, sections=SECTIONS, content=content, tables=tables, generated=generated)

    if "docx" in formats:
        try:
            from docx import Document
            from docx.shared import Pt, RGBColor
        except Exception as e:
            _fail(f"DOCX report requires python-docx: {e}")
        doc = Document()
        h = doc.add_heading(title, level=0)
        try:
            h.runs[0].font.color.rgb = RGBColor(0x0A, 0x19, 0x2F)
        except Exception:
            pass
        doc.add_paragraph(f"Generated by the Advanced Bioinformatics Platform (SynOmics) · {generated}")
        for key, label in SECTIONS:
            doc.add_heading(label, level=1)
            doc.add_paragraph(content.get(key) or "— (not provided)")
        for t in tables:
            doc.add_heading(t.get("title", "Table"), level=2)
            cols = t.get("columns", [])
            rows = t.get("rows", [])
            if cols:
                table = doc.add_table(rows=1, cols=len(cols))
                for i, c in enumerate(cols):
                    table.rows[0].cells[i].text = str(c)
                for row in rows:
                    cells = table.add_row().cells
                    for i, cell in enumerate(row[:len(cols)]):
                        cells[i].text = str(cell)
        buf = io.BytesIO()
        doc.save(buf)
        out["docxBase64"] = base64.b64encode(buf.getvalue()).decode("ascii")

    print(json.dumps(out))


if __name__ == "__main__":
    main()
