import React, { useState } from 'react';
import { 
  BarChart3, 
  Table as TableIcon, 
  Download, 
  Copy, 
  Check, 
  Search, 
  ChevronRight, 
  Layers, 
  Activity, 
  Zap, 
  Dna, 
  ExternalLink,
  ShieldCheck,
  FileSpreadsheet
} from 'lucide-react';
import { ScientificFigure, ScientificTable } from '../types';

interface ScientificFiguresAndTablesProps {
  figures?: ScientificFigure[];
  tables?: ScientificTable[];
  onExportReport?: (format: 'pdf' | 'docx' | 'json' | 'text' | 'html') => void;
}

export const ScientificFiguresAndTables: React.FC<ScientificFiguresAndTablesProps> = ({
  figures = [],
  tables = [],
  onExportReport
}) => {
  const [activeTab, setActiveTab] = useState<'figures' | 'tables'>('figures');
  const [selectedFigureId, setSelectedFigureId] = useState<string>(figures[0]?.id || '');
  const [selectedTableId, setSelectedTableId] = useState<string>(tables[0]?.id || '');
  const [tableSearch, setTableSearch] = useState('');
  const [copiedTableId, setCopiedTableId] = useState<string | null>(null);

  const activeFigure = figures.find(f => f.id === selectedFigureId) || figures[0];
  const activeTable = tables.find(t => t.id === selectedTableId) || tables[0];

  const handleCopyTableCsv = (table: ScientificTable) => {
    const headers = table.columns.map(c => `"${c.label}"`).join(',');
    const rows = table.rows.map(r => 
      table.columns.map(c => `"${String(r[c.key] !== undefined ? r[c.key] : '')}"`).join(',')
    ).join('\n');
    const csv = `${headers}\n${rows}`;

    navigator.clipboard.writeText(csv);
    setCopiedTableId(table.id);
    setTimeout(() => setCopiedTableId(null), 2000);
  };

  const filteredRows = activeTable?.rows.filter(row => {
    if (!tableSearch) return true;
    const q = tableSearch.toLowerCase();
    return Object.values(row).some(val => String(val).toLowerCase().includes(q));
  }) || [];

  // Honest empty state — no example figures/tables are shown when a real run has
  // not produced any.
  if (figures.length === 0 && tables.length === 0) {
    return (
      <div className="rounded-2xl bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B] shadow-xs p-10 flex flex-col items-center text-center">
        <div className="p-3 rounded-2xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800 text-emerald-600 dark:text-emerald-400 mb-4">
          <BarChart3 className="w-7 h-7" />
        </div>
        <h3 className="text-base font-bold text-[#0F172A] dark:text-[#F8FAFC]">No figures or tables yet</h3>
        <p className="text-xs text-[#64748B] dark:text-slate-400 mt-2 max-w-md leading-relaxed">
          Figures and tables appear here once a real analysis run produces them. No
          example results are displayed in the meantime.
        </p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Top Selector Bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 rounded-2xl bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B] shadow-xs">
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-xl bg-emerald-50 dark:bg-emerald-950/60 border border-emerald-200 dark:border-emerald-800 text-emerald-600 dark:text-emerald-400">
            <BarChart3 className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-base font-bold text-[#0F172A] dark:text-[#F8FAFC]">
              Scientific Figures &amp; Quantitative Tables
            </h3>
            <p className="text-xs text-[#64748B] dark:text-slate-400">
              Verified experimental figures and multi-omics data matrices generated by the autonomous agent architecture.
            </p>
          </div>
        </div>

        {/* Tab Toggle */}
        <div className="flex items-center gap-2">
          <div className="flex items-center p-1 rounded-xl bg-[#F3EFE6] dark:bg-[#1A2333] border border-[#E2DDD2] dark:border-[#1E293B] text-xs font-semibold">
            <button
              onClick={() => setActiveTab('figures')}
              className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all cursor-pointer ${
                activeTab === 'figures'
                  ? 'bg-white dark:bg-[#0B0F17] text-[#0F172A] dark:text-[#F8FAFC] shadow-xs'
                  : 'text-[#64748B] hover:text-[#0F172A] dark:hover:text-slate-200'
              }`}
            >
              <BarChart3 className="w-3.5 h-3.5" />
              <span>Figures ({figures.length})</span>
            </button>
            <button
              onClick={() => setActiveTab('tables')}
              className={`px-3 py-1.5 rounded-lg flex items-center gap-1.5 transition-all cursor-pointer ${
                activeTab === 'tables'
                  ? 'bg-white dark:bg-[#0B0F17] text-[#0F172A] dark:text-[#F8FAFC] shadow-xs'
                  : 'text-[#64748B] hover:text-[#0F172A] dark:hover:text-slate-200'
              }`}
            >
              <TableIcon className="w-3.5 h-3.5" />
              <span>Tables ({tables.length})</span>
            </button>
          </div>
        </div>
      </div>

      {/* VIEW 1: FIGURES */}
      {activeTab === 'figures' && (
        <div className="space-y-6">
          {/* Figure Selection Pills */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-2.5">
            {figures.map(fig => {
              const isSelected = (selectedFigureId || figures[0]?.id) === fig.id;
              return (
                <button
                  key={fig.id}
                  onClick={() => setSelectedFigureId(fig.id)}
                  className={`p-3 rounded-xl border text-left transition-all cursor-pointer flex flex-col justify-between ${
                    isSelected
                      ? 'bg-emerald-50/60 dark:bg-emerald-950/40 border-emerald-500/50 shadow-xs'
                      : 'bg-white dark:bg-[#131A29] border-[#E2DDD2] dark:border-[#1E293B] hover:border-emerald-400/40'
                  }`}
                >
                  <div className="flex items-center justify-between gap-2 mb-1.5">
                    <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded-md bg-emerald-100 dark:bg-emerald-900/60 text-emerald-700 dark:text-emerald-300">
                      Figure {fig.figureNumber}
                    </span>
                    <span className="text-[11px] font-mono text-[#64748B] dark:text-slate-400">
                      {fig.type.replace('_', ' ')}
                    </span>
                  </div>
                  <div className="text-xs font-semibold text-[#0F172A] dark:text-[#F8FAFC] line-clamp-1">
                    {fig.title}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Active Figure Showcase */}
          {activeFigure && (
            <div className="p-6 rounded-2xl bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B] shadow-xs space-y-6">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-[#E2DDD2] dark:border-[#1E293B] pb-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded-md bg-emerald-600 text-white">
                      FIGURE {activeFigure.figureNumber}
                    </span>
                    <h4 className="text-lg font-bold text-[#0F172A] dark:text-[#F8FAFC]">
                      {activeFigure.title}
                    </h4>
                  </div>
                  <p className="text-xs text-[#64748B] dark:text-slate-400 mt-1">
                    {activeFigure.subtitle}
                  </p>
                </div>
              </div>

              {/* Chart Render Area */}
              <div className="p-4 sm:p-6 rounded-xl bg-[#FAF9F5] dark:bg-[#0B0F17] border border-[#E2DDD2] dark:border-[#1E293B]">
                {/* 1. Line Chart (EPSP Electrophysiology Kinetics) */}
                {activeFigure.type === 'line_chart' && activeFigure.data.series && (
                  <div className="space-y-4">
                    {/* Key Biophysical Kinetic Metrics Badges */}
                    {activeFigure.data.meta && (
                      <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 mb-4">
                        <div className="p-2.5 rounded-lg bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B]">
                          <div className="text-[10px] font-mono text-[#64748B] dark:text-slate-400 uppercase">10-90% Rise Time (WT)</div>
                          <div className="text-xs font-bold text-emerald-600 dark:text-emerald-400">{activeFigure.data.meta.riseTime10_90_wt || '—'}</div>
                        </div>
                        <div className="p-2.5 rounded-lg bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B]">
                          <div className="text-[10px] font-mono text-[#64748B] dark:text-slate-400 uppercase">10-90% Rise Time (Pert)</div>
                          <div className="text-xs font-bold text-rose-600 dark:text-rose-400">{activeFigure.data.meta.riseTime10_90_pert || '—'}</div>
                        </div>
                        <div className="p-2.5 rounded-lg bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B]">
                          <div className="text-[10px] font-mono text-[#64748B] dark:text-slate-400 uppercase">Peak Vm (WT)</div>
                          <div className="text-xs font-bold text-emerald-600 dark:text-emerald-400">{activeFigure.data.meta.peakVoltage_wt || '—'}</div>
                        </div>
                        <div className="p-2.5 rounded-lg bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B]">
                          <div className="text-[10px] font-mono text-[#64748B] dark:text-slate-400 uppercase">Peak Vm (Perturbed)</div>
                          <div className="text-xs font-bold text-rose-600 dark:text-rose-400">{activeFigure.data.meta.peakVoltage_pert || '—'}</div>
                        </div>
                      </div>
                    )}

                    {/* Interactive SVG EPSP Waveform */}
                    <div className="relative h-64 sm:h-72 w-full">
                      <svg className="w-full h-full overflow-visible" viewBox="0 0 600 240" preserveAspectRatio="none">
                        {/* Grid lines */}
                        {[0, 60, 120, 180, 240].map((y, i) => (
                          <line key={i} x1="0" y1={y} x2="600" y2={y} stroke="currentColor" strokeOpacity="0.08" />
                        ))}
                        {/* -70mV Baseline */}
                        <line x1="0" y1="210" x2="600" y2="210" stroke="#94A3B8" strokeDasharray="3,3" strokeWidth="1" />
                        <text x="10" y="206" fill="#94A3B8" fontSize="10" fontFamily="monospace">-70 mV (Resting)</text>

                        {/* Series 1: WT (Emerald) */}
                        {activeFigure.data.series[0] && (
                          <polyline
                            fill="none"
                            stroke="#059669"
                            strokeWidth="2.5"
                            points={activeFigure.data.series[0].values.map((v: number, idx: number) => {
                              const x = (idx / (activeFigure.data.series[0].values.length - 1)) * 600;
                              // map -70..-45 to 210..30
                              const y = 210 - ((v + 70) / 25) * 180;
                              return `${x},${y}`;
                            }).join(' ')}
                          />
                        )}

                        {/* Series 2: Perturbed (Rose) */}
                        {activeFigure.data.series[1] && (
                          <polyline
                            fill="none"
                            stroke="#E11D48"
                            strokeWidth="2.5"
                            strokeDasharray="4,2"
                            points={activeFigure.data.series[1].values.map((v: number, idx: number) => {
                              const x = (idx / (activeFigure.data.series[1].values.length - 1)) * 600;
                              const y = 210 - ((v + 70) / 25) * 180;
                              return `${x},${y}`;
                            }).join(' ')}
                          />
                        )}

                        {/* Series 3: Calcium (Blue) */}
                        {activeFigure.data.series[2] && (
                          <polyline
                            fill="none"
                            stroke="#3B82F6"
                            strokeWidth="1.5"
                            points={activeFigure.data.series[2].values.map((v: number, idx: number) => {
                              const x = (idx / (activeFigure.data.series[2].values.length - 1)) * 600;
                              // map 0..2 to 210..50
                              const y = 210 - (v / 2.0) * 160;
                              return `${x},${y}`;
                            }).join(' ')}
                          />
                        )}
                      </svg>
                    </div>

                    {/* Chart Legend */}
                    <div className="flex flex-wrap items-center justify-center gap-6 pt-2 text-xs font-medium">
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-0.5 bg-[#059669]" />
                        <span>Wild-Type EPSP (mV)</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-0.5 bg-[#E11D48] border-b border-dashed" />
                        <span>Perturbed EPSP (mV)</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <div className="w-3 h-0.5 bg-[#3B82F6]" />
                        <span>Intracellular [Ca²⁺] (µM)</span>
                      </div>
                    </div>
                  </div>
                )}

                {/* 2. Bar Chart (Single-Cell TPM, SynGO FDR, GWAS Odds Ratios) */}
                {activeFigure.type === 'bar_chart' && activeFigure.data.labels && activeFigure.data.series && (
                  <div className="space-y-4">
                    <div className="space-y-3">
                      {activeFigure.data.labels.map((label: string, idx: number) => {
                        const val1 = activeFigure.data.series[0]?.values[idx] || 0;
                        const max1 = Math.max(...activeFigure.data.series[0].values, 1);
                        const pct1 = Math.min(100, Math.max(5, (val1 / max1) * 100));
                        const color1 = activeFigure.data.series[0]?.color || '#059669';

                        return (
                          <div key={idx} className="space-y-1">
                            <div className="flex items-center justify-between text-xs">
                              <span className="font-semibold text-[#0F172A] dark:text-[#F8FAFC]">{label}</span>
                              <span className="font-mono text-[#64748B] dark:text-slate-400">
                                {val1} {activeFigure.data.series[0]?.name.includes('log10') ? '-log10(FDR)' : activeFigure.data.series[0]?.name.includes('TPM') ? 'TPM' : ''}
                              </span>
                            </div>
                            <div className="w-full h-3 rounded-full bg-[#E2DDD2]/60 dark:bg-slate-800 overflow-hidden">
                              <div
                                className="h-full rounded-full transition-all duration-500"
                                style={{ width: `${pct1}%`, backgroundColor: color1 }}
                              />
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {/* Series Legend */}
                    <div className="flex items-center justify-center gap-4 pt-2 text-xs text-[#64748B]">
                      {activeFigure.data.series.map((s: any, i: number) => (
                        <div key={i} className="flex items-center gap-1.5">
                          <div className="w-3 h-3 rounded-sm" style={{ backgroundColor: s.color || '#059669' }} />
                          <span>{s.name}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              {/* Figure Scientific Caption */}
              <div className="p-4 rounded-xl bg-[#FAF9F5] dark:bg-[#0B0F17]/60 border border-[#E2DDD2] dark:border-[#1E293B] text-xs text-[#475569] dark:text-slate-300 leading-relaxed">
                <span className="font-bold text-[#0F172A] dark:text-white mr-1.5">Caption:</span>
                {activeFigure.caption}
              </div>
            </div>
          )}
        </div>
      )}

      {/* VIEW 2: QUANTITATIVE TABLES */}
      {activeTab === 'tables' && (
        <div className="space-y-6">
          {/* Table Selection Pills */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2.5">
            {tables.map(tbl => {
              const isSelected = (selectedTableId || tables[0]?.id) === tbl.id;
              return (
                <button
                  key={tbl.id}
                  onClick={() => setSelectedTableId(tbl.id)}
                  className={`p-3 rounded-xl border text-left transition-all cursor-pointer flex flex-col justify-between ${
                    isSelected
                      ? 'bg-emerald-50/60 dark:bg-emerald-950/40 border-emerald-500/50 shadow-xs'
                      : 'bg-white dark:bg-[#131A29] border-[#E2DDD2] dark:border-[#1E293B] hover:border-emerald-400/40'
                  }`}
                >
                  <div className="flex items-center justify-between gap-2 mb-1.5">
                    <span className="text-[10px] font-mono font-bold uppercase tracking-wider px-2 py-0.5 rounded-md bg-indigo-100 dark:bg-indigo-900/60 text-indigo-700 dark:text-indigo-300">
                      Table {tbl.tableNumber}
                    </span>
                    <span className="text-[11px] font-mono text-[#64748B] dark:text-slate-400">
                      {tbl.rows.length} rows
                    </span>
                  </div>
                  <div className="text-xs font-semibold text-[#0F172A] dark:text-[#F8FAFC] line-clamp-1">
                    {tbl.title}
                  </div>
                </button>
              );
            })}
          </div>

          {/* Active Table Display */}
          {activeTable && (
            <div className="p-6 rounded-2xl bg-white dark:bg-[#131A29] border border-[#E2DDD2] dark:border-[#1E293B] shadow-xs space-y-4">
              <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 border-b border-[#E2DDD2] dark:border-[#1E293B] pb-4">
                <div>
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-mono font-bold px-2.5 py-0.5 rounded-md bg-indigo-600 text-white">
                      TABLE {activeTable.tableNumber}
                    </span>
                    <h4 className="text-lg font-bold text-[#0F172A] dark:text-[#F8FAFC]">
                      {activeTable.title}
                    </h4>
                  </div>
                  <p className="text-xs text-[#64748B] dark:text-slate-400 mt-1">
                    {activeTable.description}
                  </p>
                </div>

                <div className="flex items-center gap-2 w-full sm:w-auto">
                  {/* Search Bar */}
                  <div className="relative flex-1 sm:w-48">
                    <Search className="w-3.5 h-3.5 absolute left-2.5 top-1/2 -translate-y-1/2 text-[#94A3B8]" />
                    <input
                      type="text"
                      value={tableSearch}
                      onChange={(e) => setTableSearch(e.target.value)}
                      placeholder="Search rows..."
                      className="w-full pl-8 pr-3 py-1.5 rounded-lg bg-[#FAF9F5] dark:bg-[#0B0F17] border border-[#D5CDBC] dark:border-[#1E293B] text-xs text-[#0F172A] dark:text-[#F8FAFC] placeholder:text-[#94A3B8] focus:outline-none focus:border-emerald-600"
                    />
                  </div>

                  {/* Copy CSV Button */}
                  <button
                    onClick={() => handleCopyTableCsv(activeTable)}
                    className="px-3 py-1.5 rounded-lg bg-[#F3EFE6] dark:bg-[#1A2333] hover:bg-emerald-50 dark:hover:bg-emerald-950/40 text-xs font-semibold text-[#0F172A] dark:text-slate-200 border border-[#E2DDD2] dark:border-[#1E293B] flex items-center gap-1.5 transition-colors cursor-pointer shrink-0"
                  >
                    {copiedTableId === activeTable.id ? (
                      <>
                        <Check className="w-3.5 h-3.5 text-emerald-600" />
                        <span>Copied!</span>
                      </>
                    ) : (
                      <>
                        <Copy className="w-3.5 h-3.5" />
                        <span>Copy CSV</span>
                      </>
                    )}
                  </button>
                </div>
              </div>

              {/* Data Table */}
              <div className="overflow-x-auto rounded-xl border border-[#E2DDD2] dark:border-[#1E293B]">
                <table className="w-full text-left border-collapse text-xs">
                  <thead>
                    <tr className="bg-[#FAF9F5] dark:bg-[#0B0F17] border-b border-[#E2DDD2] dark:border-[#1E293B]">
                      {activeTable.columns.map((col, idx) => (
                        <th
                          key={idx}
                          className={`p-3 font-bold text-[#0F172A] dark:text-slate-300 ${
                            col.align === 'right' ? 'text-right' : col.align === 'center' ? 'text-center' : 'text-left'
                          }`}
                        >
                          {col.label}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-[#E2DDD2] dark:divide-[#1E293B]">
                    {filteredRows.length > 0 ? (
                      filteredRows.map((row, rIdx) => (
                        <tr
                          key={rIdx}
                          className="hover:bg-emerald-50/30 dark:hover:bg-emerald-950/20 transition-colors"
                        >
                          {activeTable.columns.map((col, cIdx) => {
                            const val = row[col.key];

                            if (col.type === 'badge') {
                              return (
                                <td key={cIdx} className={`p-3 ${col.align === 'right' ? 'text-right' : col.align === 'center' ? 'text-center' : 'text-left'}`}>
                                  <span className="inline-block px-2 py-0.5 rounded-md font-mono text-[11px] font-semibold bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
                                    {String(val !== undefined ? val : '-')}
                                  </span>
                                </td>
                              );
                            }

                            if (col.type === 'pvalue') {
                              return (
                                <td key={cIdx} className="p-3 text-right font-mono text-emerald-600 dark:text-emerald-400 font-semibold">
                                  {String(val !== undefined ? val : '-')}
                                </td>
                              );
                            }

                            if (col.type === 'log2fc') {
                              const num = parseFloat(val);
                              return (
                                <td key={cIdx} className={`p-3 text-right font-mono font-semibold ${num < 0 ? 'text-rose-600 dark:text-rose-400' : 'text-emerald-600 dark:text-emerald-400'}`}>
                                  {String(val !== undefined ? val : '-')}
                                </td>
                              );
                            }

                            return (
                              <td
                                key={cIdx}
                                className={`p-3 text-[#0F172A] dark:text-[#F8FAFC] ${
                                  col.align === 'right' ? 'text-right font-mono' : col.align === 'center' ? 'text-center' : 'text-left'
                                }`}
                              >
                                {String(val !== undefined ? val : '-')}
                              </td>
                            );
                          })}
                        </tr>
                      ))
                    ) : (
                      <tr>
                        <td colSpan={activeTable.columns.length} className="p-6 text-center text-[#64748B]">
                          No records matched search filter "{tableSearch}"
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {/* Table Footer */}
              {activeTable.footerSummary && (
                <div className="text-[11px] text-[#64748B] dark:text-slate-400 italic">
                  Note: {activeTable.footerSummary}
                </div>
              )}
            </div>
          )}
        </div>
      )}
    </div>
  );
};
